### ISSUE TITLE
Definitive example?

### ISSUE THREAD

**Issue by mcpierce** [zwaldowski/semver-release-action#1]
Can you provide a complete, definitive example for using this action with preminor versions?

**Comment by mcpierce** [comment]
Specifically what I'm looking for is how to plug this action into a workflow where, when a commit is merged into develop, it tags things in this way:

1. Current tag is 0.5.0-dev.1
1. A merge happens on the develop branch.
1. New current tag is 0.5.0-dev.2

It looks like this action can do what I'm wanting (perhaps with some tweaks to our tag names), but I'm very new to Github Actions and am not sure how to use this one.

I've tried with the following:

```
name: Incremental development release tagging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: next_version
        uses: zwaldowski/match-label-action@v1
        with:
          bump: prerelease
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"
      - id: git_commit
        run: echo ::set-output name=sha::$(git rev-parse HEAD)
      - uses: zwaldowski/semver-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
```

But I only get the following error message:
<img width="512" alt="Screen Shot 2019-11-25 at 10 52 38 AM" src="https://user-images.githubusercontent.com/61601/69555797-bde76100-0f71-11ea-81e3-4066f310bdf9.png">


Can you please give an example of how I would use your action? Thank you.

**Comment by zwaldowski** [comment]
Ah, my mistake. The readme isn’t right. I’ll fix it when I get back to my desk. 

`dry_run` is only needed when you want to modify the repo using the version you just made. (I can provide that separately if you need it.) You’ll want something like:

```

- id: bump		
  name: Determine version increment
  uses: zwaldowski/match-label-action@v1
    with:
      allowed: major,minor,patch,prerelease
- name: Release version
  uses: zwaldowski/semver-release-action@v1
    with:
      bump: ${{ steps.bump.outputs.match }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by zwaldowski** [comment]
The repo's README should be fixed and expanded now. Thanks!

**Comment by mcpierce** [comment]
Sorry, but this didn't fix the issue, and didn't answer my original question about providing a full example workflow.

I copied the above into my workflow and am getting a syntax error on the action's run:

```
name: Incremental development release tagging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: bump
        name: Determine version increment
        uses: zwaldowski/match-label-action@v1
          with:
            allowed: major,minor,patch,prerelease
      - name: Release version
        uses: zwaldowski/semver-release-action@v1
          with:
            bump: ${{ steps.bump.outputs.match }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
```

But GitHub says the "with" link in id:bump is a syntax error.
